### ISSUE TITLE
DNS not responding / setup not complete?

### ISSUE THREAD

**Issue by breakall** [turboaaa/docker-nxfilter#2]
I have another DNS server listening on port 53 on my docker test box, so when I executed the docker run command, I changed the listening port:

`docker run -dit --name nxfilter -p 9053:53 -p 9080:80 -p 9443:443 nxfilter`

After the container started, I ran the following command to test:

`nslookup -port=9053 bing.com localhost`

This timed out.

I jumped into the console on the container, and ran the following test:

`nslookup -port=53 bing.com localhost`

This returned successfully:

> Server:         localhost
> Address:        127.0.0.1#53
> 
> Non-authoritative answer:
> Name:   bing.com
> Address: 13.107.21.200
> Name:   bing.com
> Address: 204.79.197.200

I tried to access the admin page on port 9080, but got the following:

> <server name> has been blocked!
> If it's blocked without a reason it might be from your browser cache.
> To clear out the cache restart your browser.

What do I need to do to get this fully set up?

**Comment by turboaaa** [comment]
Indeed an issue. I tested within the docker network as this is an upstream to another DNS server on the same network and this works. External access seems to be an issue.

**Comment by turboaaa** [comment]
Found the problem, using TCP instead of UDP.

**Comment by turboaaa** [comment]
#1

**Comment by breakall** [comment]
Confirmed working!
